# config.yml — IDEALE-EU Aerospace Digital Passport Platform
version: "1.0.0"
updated: "2025-10-22"

app:
  name: "IDEALE-EU Digital Passport"
  base_path: "/digital-passport/"
  repo: "https://github.com/IDEALE-eu/IDEALEEU.EU"
  demo: "https://aerospace-digital-pa--Robbbo-T.github.app"
  site: "https://idealeeu.eu"

data:
  component_types:
    - installation_hardware
    - information_hardware
    - antennas_sensors
    - software
    - firmware
    - model
    - primary_structures
    - secondary_structures

  # CAx lifecycle phases — corrected and expanded
  cax_phases:
    - { code: CAD, name: "Computer-Aided Design" }
    - { code: CAE, name: "Computer-Aided Engineering (Analysis)" }
    - { code: CAO, name: "Computer-Aided Optimization" }
    - { code: CAM, name: "Computer-Aided Manufacturing (Production Planning)" }
    - { code: CAI, name: "Computer-Aided Integration & Testing" }
    - { code: CAV, name: "Verification & Validation (Qualification & Certification)" }
    - { code: CMP, name: "Configuration & Change Management" }
    - { code: CAS, name: "MRO Service & Continuous Airworthiness" }

  # State progression
  state_flow:
    - QS
    - FWD
    - UE
    - FE
    - CB
    - QB

  # TFA — Threading Framework Architecture (Topic Functional Area)
  tfa:
    name: "Threading Framework Architecture"
    aka: "Topic Functional Area"
    purpose: "Fixed taxonomy for labeling, navigation, and traceability across aerospace domains."
    domains:
      - { code: AAA, title: "Airframes · Aerodynamics · Airworthiness" }
      - { code: AAP, title: "Airport · Adaptable · Platforms" }
      - { code: CCC, title: "Cockpit · Cabin · Cargo" }
      - { code: CQH, title: "Cryogenics · Quantum · H₂" }
      - { code: DDD, title: "Drainage · Dehumidification · Drying" }
      - { code: EDI, title: "Electronics · Digital · Instruments" }
      - { code: EEE, title: "Electrical · Endocircular · Energization" }
      - { code: EER, title: "Environmental · Emissions · Remediation" }
      - { code: IIF, title: "Industrial · Infrastructure · Facilities" }
      - { code: IIS, title: "Information · Intelligence · Systems" }
      - { code: LCC, title: "Linkages · Control · Communications" }
      - { code: LIB, title: "Logistics · Inventory · Blockchain" }
      - { code: MMM, title: "Mechanical · Material · Modules" }
      - { code: OOO, title: "Operations · Optimization · Outcomes (OS, Ontologies, Office UIs)" }
      - { code: PPP, title: "Propellers · Propellants · Propulsion" }

ui:
  theme:
    colors:
      primary: "oklch(0.35 0.12 250)"
      secondary: "oklch(0.55 0.01 260)"
      accent: "oklch(0.65 0.15 145)"
      special: "oklch(0.45 0.15 300)"
    typography:
      sans: "Inter"
      mono: "JetBrains Mono"
  layout:
    card_padding_px: 24
    section_gap_px: 32
    content_gap_px: 16
