# Link Checker Configuration for CONF Directory
# Validates that all relative links in markdown files resolve correctly

name: Link Checker

on:
  pull_request:
    paths:
      - '02-AIRCRAFT/MODEL_IDENTIFICATION/AMPEL360-AIR-T/ARCH/BWB-H2-Hy-E/FAMILY/Q100_STD01/CONF/**'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      
      - name: Check CONF README links
        run: |
          cd 02-AIRCRAFT/MODEL_IDENTIFICATION/AMPEL360-AIR-T/ARCH/BWB-H2-Hy-E/FAMILY/Q100_STD01/CONF
          find . -name "*.md" -exec markdown-link-check {} \;
      
      - name: Verify traceability links
        run: |
          cd 02-AIRCRAFT/MODEL_IDENTIFICATION/AMPEL360-AIR-T/ARCH/BWB-H2-Hy-E/FAMILY/Q100_STD01/CONF
          python3 .ci/verify_traceability_links.py
      
      - name: Check ICD references
        run: |
          cd 02-AIRCRAFT/MODEL_IDENTIFICATION/AMPEL360-AIR-T/ARCH/BWB-H2-Hy-E/FAMILY/Q100_STD01/CONF
          python3 .ci/verify_icd_links.py
