# CI Configuration for Aqua-QC
# Version: 1.0.0

# Python environment
python_version: "3.11"

# Test configuration
test:
  framework: pytest
  coverage_threshold: 0.80
  timeout_seconds: 600
  parallel: true
  
# Linting and formatting
lint:
  black: true
  flake8: true
  mypy: true
  max_line_length: 100

# Build configuration
build:
  install_deps: true
  dependencies:
    - "qiskit>=0.44.0"
    - "qiskit-aer>=0.12.0"
    - "qiskit-nature>=0.7.0"
    - "numpy>=1.24.0"
    - "scipy>=1.10.0"
    - "scikit-learn>=1.3.0"
    - "pytest>=7.4.0"
    - "pytest-cov>=4.1.0"
    - "pyyaml>=6.0"

# Acceptance gates
acceptance:
  noise_mitigation:
    infidelity_drop_min: 0.30
    vqe_energy_err_drop_min: 0.50
    overhead_depth_max: 3.0
    wall_time_ratio_max: 1.5
  
  qml_environment:
    f1_anomaly_min: 0.80
    rmse_drop_min: 0.10
    energy_per_inf_drop_min: 0.15
  
  shots_max: 8000
  drift_threshold:
    ro_epsilon: 0.05
    t1_epsilon: 0.10

# Reward calculation parameters
rewards:
  alpha_cost: 1.0
  alpha_energy: 0.5
  alpha_quality: 2.0
  alpha_overhead: 0.3
  alpha_walltime: 0.2
  kappa: 100.0
