# Subject Configuration
subject:
  id: SUBJ_001
  name: Example Subject
  version: "1.0"
  
effectivity:
  range: "0001-9999"
  applicability: "All aircraft in Q100_STD01 family"
  
configuration:
  baseline: BASELINE
  approval_required: true
  change_control: true
  
traceability:
  requirements:
    - REQ_001: "Structural integrity"
    - REQ_002: "Weight optimization"
  interfaces:
    - INT_001: "Connection to wing structure"
    - INT_002: "Integration with landing gear"
    
validation:
  analysis_required: true
  testing_required: true
  simulation_required: true
  
metadata:
  owner: Engineering Team
  created: 2025-10-13
  modified: 2025-10-13
  status: active
