# Artifact Configuration
artifact:
  id: 02-another-item
  name: Another Example Item
  type: analysis_report
  version: "1.0"
  
access_control:
  read: [engineering, analysis, management]
  write: [analysis]
  approve: [lead_analyst, chief_engineer]
  
workflow:
  state: draft
  submitted_date: 2025-10-13
  pending_review: true
  
versioning:
  major: 1
  minor: 0
  patch: 0
  previous_version: null
  change_summary: Initial draft
  
links:
  related_artifacts: [01-example-item]
  parent_requirements: [REQ_001]
  dependent_artifacts: []
