# TensorRT Configuration

## Engine Build Parameters
max_batch_size: 1
workspace_size_mb: 256
precision: fp16

## Optimization Profile
dynamic_shapes:
  sensor_readings:
    min: [1, 50]
    opt: [1, 50]
    max: [1, 50]

## Calibration (for INT8)
calibration:
  enabled: false
  cache_file: calibration.cache
  algorithm: ENTROPY_CALIBRATION_2
  
## Runtime Settings
dla_core: -1  # -1 = disabled (use GPU)
gpu_fallback: true
