openapi: 3.1.0
info:
  title: "[Model/Component Name] API"
  version: "[e.g., 1.0.0]"
  description: "[Brief description of API purpose]"
  contact:
    name: "[Team Name]"
    email: "[email]"

servers:
  - url: "[e.g., https://api.ideale-eu.org/component/v1]"
    description: Production API

security:
  - OAuth2: []
  - mTLS: []

paths:
  /endpoint1:
    get:
      summary: "[Brief description]"
      parameters:
        - name: param1
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'

components:
  schemas:
    ResponseSchema:
      type: object
      properties:
        field1:
          type: string
        field2:
          type: number

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.ideale-eu.org/oauth/token
          scopes:
            read:data: Read data
    mTLS:
      type: mutualTLS

x-rate-limit:
  requests_per_minute: 100
