# .github/workflows/structure-scan-copilot.yml
name: Structure Scan + Copilot

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run structure scan
        run: |
          python3 scripts/structure_scan.py \
            --repo-root . \
            --markers pyproject.toml setup.py requirements.txt package.json CMakeLists.txt Makefile .gitmodules \
            --readme-names README.md README.rst README.txt

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: structure-scan-report
          path: structure-scan-report/*

      - name: Add summary
        if: always()
        run: |
          echo "## Structure Scan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Open points**" >> $GITHUB_STEP_SUMMARY
          if [ -s structure-scan-report/open_points.txt ]; then
            sed -n '1,300p' structure-scan-report/open_points.txt >> $GITHUB_STEP_SUMMARY
          else
            echo "none" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**End path points**" >> $GITHUB_STEP_SUMMARY
          sed -n '1,300p' structure-scan-report/end_points.txt >> $GITHUB_STEP_SUMMARY || true

      - name: Annotate PR with warnings
        if: always()
        run: |
          if [ -s structure-scan-report/open_points.txt ]; then
            while IFS= read -r d; do
              [[ -z "$d" ]] && continue
              echo "::warning file=${d}::Folder lacks README and packaging markers"
            done < structure-scan-report/open_points.txt
          fi

      - name: Prepare Copilot prompt
        id: prep
        run: |
          if [ -s structure-scan-report/open_points.txt ]; then
            OPEN_POINTS=$(sed 's/^/- /' structure-scan-report/open_points.txt | tr -d '\r')
          else
            echo "has_open=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          cat > copilot_prompt.md << 'EOF'
@copilot

Task: For each path below that lacks a README and packaging marker, generate:
1) A directory tree proposal for that path only. Return in a fenced code block.
2) A `README.md` draft per path covering: purpose, architecture, interfaces/APIs, file layout, ownership, testing, and airworthiness/compliance notes suitable for EASA submissions; include “Next steps”.
3) Propose file additions as a new pull request targeting this branch. Include proposed commit messages and file diffs.

Paths to process:
EOF
          printf "\n%s\n" "$OPEN_POINTS" >> copilot_prompt.md
          echo "has_open=true" >> $GITHUB_OUTPUT

      - name: Comment on PR with @copilot
        if: steps.prep.outputs.has_open == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('copilot_prompt.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Open or update issue with @copilot
        if: steps.prep.outputs.has_open == 'true' && github.event_name != 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('copilot_prompt.md', 'utf8');
            const {owner, repo} = context.repo;
            const title = "Copilot: generate directory trees and READMEs for open points";
            const { data: issues } = await github.rest.issues.listForRepo({
              owner, repo, state: 'open', per_page: 100
            });
            const existing = issues.find(i => i.title === title);
            if (existing) {
              await github.rest.issues.createComment({ owner, repo, issue_number: existing.number, body });
            } else {
              await github.rest.issues.create({ owner, repo, title, body });
            }

      # Optional: fail CI when open points exist
      - name: Fail on open points
        if: steps.prep.outputs.has_open == 'true'
        run: |
          echo "Open points detected"
          exit 1
